services:
  postgres:
    image: postgres:18
    container_name: ecom_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pdf-service:
    build: ./pdf-service
    container_name: ecom_pdf_service
    ports:
      - "4000:4000"
    networks:
      - back-net
    restart: always

  backend:
    build: ./backend
    container_name: ecom_backend
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      PDF_SERVICE_URL: ${PDF_SERVICE_URL}

      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL:-http://host.docker.internal:4566}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-ecom-localstack-storage}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - back-net
      - front-net
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

  worker:
    build: ./worker
    container_name: ecom_worker
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL:-http://host.docker.internal:4566}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-ecom-localstack-storage}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - back-net

  frontend:
    build: ./frontend
    container_name: ecom_frontend
    ports:
      - "8080:80"
    networks:
      - front-net
    depends_on:
      - backend

  localstack:
    image: localstack/localstack-pro:latest
    container_name: ecom_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,s3,iam,sts
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - back-net
    profiles:
      - with-localstack

volumes:
  pgdata:

networks:
  back-net:
    driver: bridge
  front-net:
    driver: bridge