version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: ecom_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: ecom_backend
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - back-net
      - front-net
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

  worker:
    build: ./worker
    container_name: ecom_worker
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - back-net

  frontend:
    build: ./frontend
    container_name: ecom_frontend
    ports:
      - "8080:80"
    networks:
      - front-net
    depends_on:
      - backend

volumes:
  pgdata:

networks:
  back-net:
    driver: bridge
  front-net:
    driver: bridge